apiVersion: v1
kind: Service
metadata:
  name: outbox-publisher
  namespace: ecommerce
  labels:
    app: outbox-publisher
spec:
  selector:
    app: outbox-publisher
  ports:
    - name: metrics
      port: 8001
      targetPort: 8001
