apiVersion: v1
kind: Service
metadata:
  name: inventory-worker-headless
  namespace: ecommerce
  labels:
    app: inventory-worker
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: inventory-worker
  ports:
    - name: metrics
      protocol: TCP
      port: 8002
      targetPort: metrics
