apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-worker
  namespace: ecommerce
  labels:
    app: inventory-worker
spec:
  serviceName: inventory-worker-headless
  replicas: 3
  podManagementPolicy: Parallel

  selector:
    matchLabels:
      app: inventory-worker

  template:
    metadata:
      labels:
        app: inventory-worker
    spec:
      serviceAccountName: inventory-worker
      terminationGracePeriodSeconds: 30

      containers:
        - name: inventory-worker
          image: 827913617635.dkr.ecr.us-east-1.amazonaws.com/inventory-worker:5a6713cc93cb00a53a2f214e256576a115117831
          imagePullPolicy: Always

          ports:
            - name: metrics
              containerPort: 8002
              protocol: TCP

          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-db-secret

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: METRICS_PORT
              value: "8002"
            - name: KINESIS_ITERATOR_TYPE
              value: "TRIM_HORIZON"
            - name: KINESIS_RECORDS_LIMIT
              value: "1000"
            - name: KINESIS_POLL_INTERVAL_SEC
              value: "0.2"

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"

          readinessProbe:
            tcpSocket:
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
