apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: ecommerce
  labels:
    app: order-api

spec:
  replicas: 2

  # 롤링 업데이트 중 추가 Pod를 만들지 않고
  # 기존 Pod 1개를 먼저 종료하여 Pod 슬롯을 확보
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
      
  selector:
    matchLabels:
      app: order-api

  template:
    metadata:
      labels:
        app: order-api

    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: order-api

      containers:
        - name: order-api

          # ECR 생성 후 실제 이미지 주소로 변경
          image: 827913617635.dkr.ecr.us-east-1.amazonaws.com/order-api:564a5d27f69c862b370ed1c633a56e02729f918d
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-db-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3