apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: ecommerce
  labels:
    app: order-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: order-api

  template:
    metadata:
      labels:
        app: order-api

    spec:
      containers:
        - name: order-api

           # ECR 생성 후 실제 이미지 주소로 변경
          image: 827913617635.dkr.ecr.us-east-1.amazonaws.com/order-api:5a6713cc93cb00a53a2f214e256576a115117831
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-db-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3