apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  AWS_REGION: "us-east-1"
  DB_PORT: "3306"
  DB_NAME: "ecommerce"
  KINESIS_STREAM_NAME: "ecommerce-order-events"
  LOG_LEVEL: "INFO"